apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    # No Role/RoleBinding is created for this SA -> it has zero permissions.
    devsecops.io/zero-perm: "true"
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
